name: DarthCraft
version: 2.3.2
description: Custom plugin for DarthCraft
softdepend: [Votifier]
authors: [DarthSalamon, Wild1145]
main: net.darthcraft.dcmod.DarthCraft
commands:
  ban:
    description: Bans a player
    usage: /<command> <player> <reason>
  banip:
    description: Bans the last Ip of a player (or all)
    usage: /<command> [-a] <player> <reason>
  unban:
    description: Unbans a player and all attached IPs
    usage: /<command> <player>
  o:
    description: Says a message in AdminChat
    usage: /<command> [message]
  setrank:
    description: Sets (forcefully) the rank of a player
    usage: /<command> [-f] <player> <guest|member|loyal|admin|pradmin|headadmin|host>
  trollmode:
    description: Trololol
    usage: /<command> <on|off>
  mute:
    description: Mutes a player
    usage: /<command> <player>
  unmute:
    description: Unmutes a player
    usage: /<command> <player>
  kick:
    description: Kicks a player
    usage: /<command> <player> <reason>
  tempban:
    description: Temporarily bans a player
    usage: /<command> <player> <timeoffset> <reason>
  darthcraft:
    description: Shows information about DarthCraft, the plugin that runs it or reloads the config.
    usage: /<command> [<plugin | reload>]
    aliases: [dc]
  like:
    description: Like DarthCraft!
    usage: /<command> [<amount | set | remove>]
  busy:
    description: Toggles busy status
    usage: /<command>
  topic:
    description: Generates a random topic of discussion from the configuration file
    usage: /<command>
  warn:
    description: Warns a player and issues appropriate infraction points
    usage: /<command> <player> <amount> <reason>
  invade:
    description: A pointless command to mess with Jake
    usage: /<command> <player>
  report:
    description: Allows you to report a player for what ever reason to the in game staff. 
    usage: /<command> <player> <reason>
  christmas:
    description: Merry Christmas from the mad developer!
    usage: /<command>
  delwarn:
    description: Allows a head admin or host to remove warning points if appropriate. 
    usage: /<command> <player> <amount> <reason>
  getwarnings:
    description: Allows a player to get their own warning points and reasons, or a admin to see a players warning points and reasons.
    usage: /<command> [player] 
  setlogin:
    description: Allows a player to set their own login message
    usage: /<command> <message>
  dellogin:
    description: Allows a player to remove their own login message, or for a admin to remove someone elses.
    usage: /<command> [Player]
  stfu:
    description: Mutes a player but not being quite so polite. 
    usage: /<command> <player>